name: eazy
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  
  
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  device_preview:
  google_fonts: ^6.2.1
  flutter_svg: ^2.1.0
  image_picker: ^1.1.2
  dartz: ^0.10.1
  get_it:

dev_dependencies:
  integration_test:
      sdk: flutter
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0
  mocktail: ^1.0.4
  bloc_test: ^10.0.0


flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/svgs/
    - assets/
    - assets/images/
    - packages/
