name: eazy
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  device_preview: ^1.1.0
  google_fonts: ^6.2.1
  flutter_svg: ^2.1.0
  image_picker: ^1.1.2
  flutter_bloc: ^9.1.1
  dartz: ^0.10.1
  get_it: ^7.7.0
  lottie: ^2.7.0
  otp_text_field_v2:
  flutter_localization:
  smooth_page_indicator: ^1.2.1
  animated_bottom_navigation_bar: ^1.4.0
  flutter_native_splash: ^2.4.4
  modal_progress_hud_nsn: ^0.5.1
  url_launcher:

dev_dependencies:
  flutter_test:
    sdk: flutter

  integration_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/svgs/
    - assets/
    - assets/images/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf